[package]
name = "deduplicator"
version = "0.2.2"
edition = "2021"
description = "find,filter,delete Duplicates"
repository = "https://github.com/sreedevk/deduplicator"
license = "MIT"
authors = [
    "Sreedev Kodichath <sreedevpadmakumar@gmail.com>",
    "Valentin Bersier <vbersier@gmail.com>",
    "Dhruva Sagar <dhruva.sagar@gmail.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bytesize = "1.1.0"
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
colored = "2.0.0"
dashmap = { version = "5.4.0", features = ["rayon"] }
globwalk = "0.8.1"
gxhash = "3.4.1"
indicatif = { version = "0.17.2", features = ["rayon"] }
itertools = "0.10.5"
memmap2 = "0.5.8"
pathdiff = "0.2.1"
prettytable-rs = "0.10.0"
ratatui = "0.29.0"
rayon = "1.6.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
threadpool = "1.8.1"
unicode-segmentation = "1.10.0"
uuid = { version = "1.17.0", features = ["v4"] }
vfs = "0.12.1"

[profile.release]
strip = true

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
rust-toolchain-version = "1.78.0"
ci = ["github"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]
cargo-dist-version = "0.0.7"
